### ISSUE TITLE
Update topic to follow the WIS2 specification

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/GTStoWIS2#103]
The topic value generated by GTStoWIS2 is missing "data" and data policy. 

My suggestion would be to add "/data/core" to the fulltopic in between subtopic_cccc and the following subtopics.

An alternative would be to add another table listing "core" or "recommended" for all entries of Volume C1 and replace the hard coded "core" with the correct table entry.

**Comment by antje-s** [comment]
It is included in TableA.json. It can be set or adjusted so flexibly for each TTAAii recommended or core. I have already tried to switch to recommended for aviation products.
