### ISSUE TITLE
AHLtoTopic() loses one topic level

### ISSUE THREAD

**Issue by snus8bit** [wmo-im/GTStoWIS2#106]
AHL to topic conversion returns one less level if country is unknown.  
'IPRN86_RUDL_121400' -> 'rus.rudl.data.core.weather.surface-based-observations.radar'  
'IPRN87_RASM_121400' -> 'unknown.data.core.weather.surface-based-observations.radar'  
7 levels vs 6.
Maybe _getSubtopic_CCCC() should return 'unknown/unknown'  ?

**Comment by antje-s** [comment]
Sorry for the late response, your proposal was goot, but for WIS2 Transition it is decided to use TTAAii for the WIS2 Topic Hierarchy (WTH) in the implementation of GTStoWIS2 gateways, see also
https://github.com/wmo-im/wis2-transition-guide/blob/main/transition-guide/sections/gts_to_wis2_gateway.adoc 
Therefore, the code and the values contained in the tables for the mapping are no longer maintained
