### ISSUE TITLE
Why Message Queueing Protocols (MQP)?

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#12]
With Tokyo cloud project presentation from Noyori-san ( @public-tatsuya-noyori ) raised the question of why bother with MQP at all, when one can do folder replication.  Does MQP add value?

Using cloud for storage as recommended by Japan is not a problem, and fully expected to be done by many centres. The question being investigated in this issue is replacing a MQP notification layer with a set of shell scripts and a delta calculation mechanism.

Outline:

* MQP is a way of distributing updates more efficiently than is possible with whatever delta method can be devised. Need to document that discussion.
 
* It is not clear what the underlying standards in use by Tokyo cloud project are to permit additional implementations.  What is being proposed as a standard? What algorithms can be reproduced by someone else?

* Application of MQP to this problem is a straightforward use of open/freely available technologies present in the wider world.  It makes it easier for others to adopt. Cloud is a wide array of disparate methods... not clear what is being standardized, not clear how wide scope of tools centres would need to support/adopt.

**Comment by petersilva** [comment]
background:

* https://github.com/MetPX/sarracenia/blob/master/doc/sarra.rst#why-not-just-use-rsync

* https://github.com/MetPX/sarracenia/blob/master/doc/hpc_mirroring_use_case.rst

   Summary of the mirroring use case (mirroring 27 million files continuously in real-time.)

   * Need to understand how the index/updates are calculated. In the implementations we have so far seen, there needs to be some mechanism on the server to traverse the file tree to find the files that have been added.  The speed of traversal is quite limited in practice, and provides a lower bound on the polling frequency that increases with the size of the tree.  Using rsync, which traverses the entire tree every time, the minimum polling interval was about 6 hours.  We initially implemented a solution relying on the IBM General Parallel File System which is database oriented, and using queries of all files modified since time X.  Even in that case, the queries took minutes to execute and provided a lower bound on the polling frequency.   We could get it down to about five to ten minutes (but sometimes a few minutes longer... as query performance also depended on file system load)

   * We are now using a shim library, where the process writing the file produces a post. There is no polling of the tree at all. The notifications propagate sub-second, and the files are mirrorred in a few minutes, bounded only by the number of active copy processes. The load on all systems is much lower, and everyone experiences much better file system i/o because the load of the polling traffic is removed.

The demonstrations in the Tokyo cloud talk demonstrate good performance, but for very small use cases.  It is unclear how the index files are generated.   

* Are the index files generated by the publisher, or the consumer? (is there one index file per unit time that the consumers all download?) or does each consumer need to build their own index files.

* how is file completion dealt with ( if a file is partially transferred at the time an index is generated, what happens?)

would need to understand how the index files are built to understand how it will scale to larger use cases.

**Comment by petersilva** [comment]
@public-tatsuya-noyori Can you clarify the two bullet points at the end of the comment above about how the indexes are created in the Tokyo Cloud method?

**Comment by petersilva** [comment]
@public-tatsuya-noyori has clarified that a file is only added to the index files after it is completely devliered which answers the file completion worry. but how the index files are build is not yet clear to me.

**Comment by public-tatsuya-noyori** [comment]
To share our discussion, I copy and paste our email's discussion as follows.

Best regards
Tatsuya

#### From Peter-san

Hello Noyori-san,

Thank you very much for your talk today. File completion is taken care of by only adding to the index when the file is complet. Clear and good. A remaining question is about how the index file itself built?

Timo and I created an issue to discuss the issues raised by your talk:
https://github.com/wmo-im/GTStoWIS2/issues/12

Perhaps better to continue the discussion over there.

Thanks


#### From me

Dear Peter-san,

Thank you for your organization.

> A remaining question is about how the index file itself built?

It would be appreciated if you could read the following part of Tokyo cloud project html site.
https://public-tatsuya-noyori.github.io/tokyo_cloud_project/cloud_project#directory-name-convention


The code of "met_pre_batch_to_cache.py" is on GitHub, you can install "met_pre_batch_to_cache.py" as follows.

git clone https://github.com/public-tatsuya-noyori/meteorological_preprocessor
cd meteorological_preprocessor
pip3 install .

Also, you can see the help of "met_pre_batch_to_cache.py" as follows.

met_pre_batch_to_cache -h


Also, you can run "met_pre_batch_to_cache.py" as follows.

met_pre_batch_to_cache RJTD input_file_directory/WMO_MESSAGE_FILES_OR_BATCHED_FTP_FILES  output_file_directory 1> `date -u "+%Y%m%d%H%M%S"`.txt


The outputfile of `date -u "+%Y%m%d%H%M%S"`.txt is a index file.

Best regards
Tatsuya

#### From Peter-san

Things we will perhaps agree on more easily:

There should be a hierarchical directory tree hosted on many servers. In MQP, the hiearchy is called topic/subtopics... in tokyo cloud they are categories/sub-categories. Tokyo cloud is using one topic scheme, for example, you have "inclusive pattern"

$ vi inclusive_pattern.txt
/alphanumeric/surface/synop/

The 'alphanumeric/surface/synop/' is a mapping of TTAAii to topics. Antje and I have been working on such a mapping, it is the main point of the GTStoWIS2 module. We take all of the WMO386 tables, and map them to a common topic tree. What is your scheme for defining "categories" for inclusive patterns?



more questions about how it works:


Can I use this on a normal, non-cloud server, such as a raspberry pi, or must I use a cloud storage mechanism?


What is the upstream source of data?


#### From me

Dear Peter-san

> What is your scheme for defining "categories" for inclusive patterns?

The inclusive pattern is regex pattern.
Also, exclusive pattern is needed to reduce maintenance cost of the routing catalogues.
https://public-tatsuya-noyori.github.io/tokyo_cloud_project/pub_sub_clone_operations#to-reduce-maintenace-cost-of-the-routing-catalogues

The topic tree of MQTT supports only wildcard pattern of "+", "#", "*". I think regex pattern is needed.


The "categories" is defined by the following CSV.
https://github.com/public-tatsuya-noyori/meteorological_preprocessor/blob/master/src/meteorological_preprocessor/conf_batch_to_cache.csv

> Can I use this on a normal, non-cloud server, such as a raspberry
> pi, or must I use a cloud storage mechanism?

ceph or minio. But, I have never use them.


> What is the upstream source of data?

The source data is all GTS data.


Best regards,
Tatsuya

**Comment by petersilva** [comment]
decks being prepared to provide background/motivation. to be presented & discussed at January commitee meeting.
