### ISSUE TITLE
download scheme (protocols) to permit in messages

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#13]
Current experiments with messages include https as the sole payload download protocol.  The Canadian implementation additionally supports (and extensively uses) sftp (Secure Shell file transfer protocol) as a payload download protocol.  The grammar in the messages does not prevent writing any scheme in a URL, but we probably want to limit the number of schemes centres need to support.

The client needs to support each schema in order to make use of the resources being announced.  Perhaps maintain a list of schemes to be approved, and stipulate that they be non-proprietary.

**Comment by petersilva** [comment]
https://github.com/wmo-im/GTStoWIS2/tree/main/message_format

The README.rst file in that directory contains a paragraph listing accepted schemes as:  https, sftp, ftp.

We can bless that file as the canonical source, and only change it with committee blessing.

**Comment by petersilva** [comment]
closing as the proposal is in the repository now.  We can debate additions as a separate issue.

**Comment by petersilva** [comment]
commitee suggest removing FTP.

**Comment by petersilva** [comment]
Discussed, and some word smithing done.  updated text prepared for review. 
( 3423c02d9eb3c686743be03b45fe5f7584f43d24 )

**Comment by Jolik** [comment]
> commitee suggest removing FTP.... and keeping FTP... and removing restrictions on protocols.
> do we allow S3? ipfs? ?
> 
> worries about clients not having all the protocol support necessary to download selected date.
> 
> david threatened us ftps.

Sorry for interfering!

Please tell me, is the SFTP protocol that is defined in the WIS 2.0 document is it exactly SSH File Transfer protocol (https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol) or is it a typo and means FTP Secure protocol (https://en.wikipedia.org/wiki/FTPS) ?

Thanks for the answer!

**Comment by petersilva** [comment]
We mean to include (as SFTP) the SSH_File_Transfer_Protocol, and explicitly not FTPS.  This was a hot topic  in committee and FTPS was explicitly excluded. The reference to David (Podeur) ¨threatening us with ftps¨ was semi facetious in reference to those discussions.  So far, we are trying to avoid/resist/refuse FTPS... as SFTP is a much better solution to that problem.

**Comment by Jolik** [comment]
> We mean to include (as SFTP) the SSH_File_Transfer_Protocol, and explicitly not FTPS. This was a hot topic in committee and FTPS was explicitly excluded. The reference to David (Podeur) ¨threatening us with ftps¨ was semi facetious in reference to those discussions. So far, we are trying to avoid/resist/refuse FTPS... as SFTP is a much better solution to that problem.

Thanx!
