### ISSUE TITLE
new topic version submitted

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#14]
@antje-s sent me some new topics, but the evaluation process involves some work.  It is probably better to document it here, rather than leave things hanging for months.

[mergeTopic.zip](https://github.com/wmo-im/GTStoWIS2/files/5617376/mergeTopic.zip)

**Comment by petersilva** [comment]
The normal way to look at changes in the topic tables is to run them through the validator. as described in the README.
so I did:
```

git clone https://github.com/wmo-im/GTStoWIS2
cd GTStoWIS2
git branch issue14
cd GTStoWIS2 
unzip ~/Downloads/mergeTopic.zip
cd ..
python3 test.py

```
and that should run the existing python library, using the new tables, to parse the set of sample bulletins in AHL_examples.txt
Result?

```
fractal% python3 test.py
test.py
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableA.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC1.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC2.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC3.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC4.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC5.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC6.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableC7.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableCCCC.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableGISC.json
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableB.csv 
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableD2.csv 
reading TableD1
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableD1.csv 
reading TableD3
reading /home/peter/GTStoWIS2/issue14/GTStoWIS2/TableD3.csv 
Tests, count: 305
input:   1 - UARA61_RUMG_161116_445a58ea753d18b066cf872b90c517e2.txt
topic from CCCC RUMG -> magadan (country: ru )
ahlpib: ['air/aircraft', '', 'Aircraft reports', 'FM 41 (CODAR)', ' ICAO (AIREP)\n']
topic from TT/B  "UA" -> "air/aircraft" 
AATopic 1 input: TT=UA, AA=RA, ahlHint={'topic': 'upperair', 'T2': 'B', 'A1': 'C1', 'A2': '', 'ii': '', 'priority': '2'}
AATopic 7 self.a1topic=self.tableC1[RA]["topic"]
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    t = topic_builder.analyzeAHL(ahl)
  File "/home/peter/GTStoWIS2/issue14/GTStoWIS2/__init__.py", line 325, in analyzeAHL
    AATopic=self.__AATopic(TT,AA,ii,CCCC,ahlParseHint) 
  File "/home/peter/GTStoWIS2/issue14/GTStoWIS2/__init__.py", line 247, in __AATopic
    exec( "self.a2topic=self.table"+a2+"[AA]"+idx )
  File "<string>", line 1, in <module>
AttributeError: 'GTStoWIS2' object has no attribute 'table'
fractal% 

```

So the tables have been changed in a way which renders them incompatible with the testing methodology. Ideally, when changing the tables' format, people would update the python routines in GTStoWIS2/__init__.py to be compatbile with the new tables, so that the checks pass.  Since that isn't done.  This issue will walk through the update process.

```

git reset --hard
cd ..
mkdir Antje_1020
cd Antje_1020
unzip ~/Downloads/mergeTopic.zip
cp TableA.json ../GTStoWIS2/

```

Start by changing only TableA, and see what is broken.

**Comment by petersilva** [comment]
Running the tests again, it fails the same way.  so now have to look at the code to understand the different processing of TableA.

**Comment by antje-s** [comment]
@petersilva  
[mergeTopic.zip](https://github.com/wmo-im/GTStoWIS2/files/5617640/mergeTopic.zip)


script TTAAii_merge.py 
is just to get an overview list of the topics, here is the latest version with ttaa at the beginning of each line

**Comment by antje-s** [comment]
There are some changes:
- TableA.json
--> split AA field to A1 and A2 (A2 is empty if not needed), to avoid mix AA and A1/A2 fields
--> renaming "Description" to "topic" (to clarify it is first topic-part)

- TableB,json
--> json file instead of csv,  for uniformity

- TableC1.json/TableC2.json/TableC3.json/TableC4.json/TableC5.json
--> no changes to structure
--> changed e.g.
C2: "Y": "sea/missing"
to
C2: "Y": "sea/missing_c2_y"

- TableC6.json
--> splitted into TableC6_I.json and TableC6_J.json
--> content changes

TableC7.json
--> "ii" values reduced to the upper limit (comparing in script easier)

TableD1.csv-TableD3.csv
--> not used

TableCCCC.json
--> no changes

**Comment by antje-s** [comment]
[getTopic.zip](https://github.com/wmo-im/GTStoWIS2/files/5617860/getTopic.zip)
getTopic - need to be updated for splitting TableC6.json

**Comment by antje-s** [comment]
Should we delete/close old branches and open a new one?

**Comment by petersilva** [comment]
branch issue14 created, with a complete re-write of the parsing module, accepting all the all JSON encoded tables.
@antje-s should recognize a lot of the code in the re-write, as a lot of it is copied.  Please try out the module, and do not submit new changes unless accompanied by parser module (GTStoWIS2/__init__.py ) changes that match table changes.

Hopefully now that everything is all JSON, there should be less of that. The module now interprets the input AHL properly whether it starts with TTAAii or has the A_ prefix. So it should be directly usable in other peoples' stacks.

It runs against the test cases ( run python3 test.py and it parses the 300 or so examples in AHL_examples.txt ) if you have test AHL's to add please add them to the file.

My server is currently broken... I cannot make changes to the hpfx.collab tree for a few days.  Will implement as soon as possible.

**Comment by petersilva** [comment]
OK merging anyways.  This version is certainly better than what we had.  If anything is broken by it, we will improve these
tables rather than working from the old ones.
