### ISSUE TITLE
Server-Side Filtering is a requirement for MQP

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#15]
attached is a small model of effects on server bandwidth of different dissemination schemes, trying to illustrate the effect of different filtering schemes on resource utilisation. It is not very obvious, but it may communicate the concept. 

If you operate a data pumping node, you can serve clients with many different schemes:

GTS: just forward all the data to each of your clients. There is no index, only data.

This is the old method that does not permit downstream to modulate the data feed at all. Clients receive a firehose and discard was is not of interest to them. Server and client both pay to download that "uninteresting" data.  Server-side "filtering" was accomplished out of band, by having humans communicate and routing tables tuned, but it is generally painful, and ideally human interaction server side should not be needed to effect client selections.

In all the more modern proposals, there is the idea of client-side selection. To enable client-side selection of data to download, you need to build an index of all the products, and each index entry will take some space. Also, the actual selective downloads by the client typically add a little overhead.

RPI: Replicating Peer with Index.

The "worst case" when the client just wants to copy the entire tree, you end up just transferring the index in addition to all the data. In addition, since client downloads data, rather than it being sent pro-actively, there is some extra overhead for that. This consumes more bandwidth on the server (and the clients) than plain old GTS.

The above two cases are what one would expect for communication amongst GISC nodes, where the "entire" tree would be replicated.  So far there is little benefit to additional metadata, if there is no selection, then the index is no use. For indices to have value, they need to be used to select subsets of data. This functionality is not exercised in the use case of GISC to GISC replication.

There is a hope that instead of adopting a particular method only for exchange among GISC peers, we have a method that can be applied to general dissemination to clients. In the Canadian data mart, for example, we have a single data mart providing raw data for hydrology, numerical weather prediction, radar products, satellite imagery, as well as traditional alphanumeric and station data in BUFR and Canadian XML formats, and CAP for alerts. The only client that would want to reproduce the entire data mart would be say, to make an additional instance in the cloud. Most clients want particular subsets of data, and the index is the means for enabling selective download (typically by dataset.)

CSF: Client Side Filtering.

To use client-side filtering, one creates an index of all products being replicated, and then the client looks over the index, and finds the subset that they are interested in. Typically some sort of regular expression or pattern matching mechanism is used. The client needs to transfer the entire index in order to apply selection filters.

This method is what is effectively implemented with message queues that pass all data on un-conditionally. Typically the case with Apache Kafka, or using AMQP with a fanout exchange.

Each client downloads the entire index, and the specific data they are interested in, with some overhead.

SSF: Server-side Filtering

Some message queueing protocols include hierarchical topics. MQTT has them natively, with AMQP 0.9*, there is the choice of "topic exchanges" that provide similar function. * With Server-side filtering, the clients connecting to the server specify a subset of the index of data they are interested in. The server only sends that subset of the index to the client. If most or all clients are interested in a small subset of the data, then the savings from transferring a subset of the index can be considerable.

In the attached spreadsheet model, one can see the total volume of data the dissemination server needs to pump to serve a number of clients (left column) varying from 10 to 100 clients. The assumptions are in the lower rows of that spreadsheet and can be changed to experiment with. In the second sheet, there is a graph of sorts, but Excel isn't letting me label it properly, so it isn't terribly clear.

If you have extreme subsets (which is close to real with current Canadian experience, but totally different from transfers between GISC nodes), then one sees 10:1 or 100:1 bandwidth savings by using server-side filtering. While the results depend on how you set the assumptions, it is fairly clear that very significant savings in bandwidth usage can be obtained. These savings are most obvious on the server side, but each client will see proportional savings as well. That this is a real benefit is evident in the struggles NWS is going through at the moment, trying to shed some dissemination load.

Another way of getting the same effect would be to have multiple indices. In AMQP 0.9, the multiple indices effect would be produced by using multiple exchanges, in a file-based arrangement like Tokyo Cloud, one would produce multiple independent index file series presumably sergrated by data type. The mechanisms for establishing different indices will vary by MQP/mechanism.

I don't know what AMQP 1.0 provides in this area. keyword exchanges are not the same as topic ones, would need to understand whether server-side pattern matches were discarded, retained or improved.

So to me the question is, do we make SSF a baseline requirement for MQP's? I was originally taking server-side filtering for granted, but I realize that others are not doing so, so it is something to be discussed.

[data_volume_model.xlsx](https://github.com/wmo-im/GTStoWIS2/files/5727666/data_volume_model.xlsx)

**Comment by petersilva** [comment]
[data_volume_model.xlsx](https://github.com/wmo-im/GTStoWIS2/files/5725673/data_volume_model.xlsx)

**Comment by efucile** [comment]
@petersilva thank you for this very interesting analysis. I have few questions.
1. Are we going to make a different choice for the exchange between GISCs, the access provided to a generic user and the upload from a NC or DCPC, or a single observing station?
2. How do we relate the protocol level filtering with the WIS DAR catalogue? The catalogue provides the search capability that make data streams findable and could provide a way to have preset filtering patterns.

**Comment by petersilva** [comment]
@efucile 

> Are we going to make a different choice for the exchange between GISCs, the access provided to a generic user and the upload from a NC or DCPC, or a single observing station?

Good question.  I hope we do not need difference choices, and if we use an any MQP, then the same mechanism works seamlessly in both cases. My first guess would be that upload from an NC or a DCPC would involve the NC or DCPC producing their own national index, and distributing their tree, and then a GISC having a role of combining the indices of the NC's to create an overall index. With MQP's, combining index entries from multiple sources is just normal, the messages are all posted to the same AMQP exchange and building an index with multiple writers just works. 

While composition of multiple inputs is a strength of MQP as it is inherently an interprocess communications (IPC) mechanism. With files, it is less natural and less obvious. One must introduce a different IPC method, such as semaphores, or file locking, to mediate access by multiple writers to cooperatively build an index. A way of getting around having to combine national indices would be to replicate a separate index for each country. so one would subscribe to a separate channel, or index, per upstream country. In such a scheme, a GISC would have to subscribe to a number of national indices/channels perhaps x 5 for priority levels? Perhaps there are other ideas?


> How do we relate the protocol level filtering with the WIS DAR catalogue? The catalogue provides the search capability that make data streams findable and could provide a way to have preset filtering patterns.

WIS/DAR search is inherently much more flexible than what can be achieved with hierarchical topics.  WIS/DAR attributes are not ordered.  I imagine that once the topic hiearchy is understood and standardized, including the mapping from AHL -> topic, that the output of a WIS/DAR search will include a list of canonical hierarchical topics.  That topic list can be used for download clients to subscribe to the subset of the distribution channel (aka index) that is of interest to them. It is likely that additional client-side filtering will be needed.

**Comment by josusky** [comment]
@petersilva Server side filtering through topics and "binding key" (I guess that is the official AMQP 0.9.1 term for things like "some.*.cool.topic.#" works also with AMQP 1.0. It is worth mentioning that wild cards in the binding key are not mentioned in https://www.rabbitmq.com/amqp-0-9-1-reference.html. And in turn, in AMQP 1.0 interpretation of endpoint address as "exchange/binding-key" is more a server/broker feature than a true protocol feature. So far, for the standardization of what is popular.
In addition, AMQP 1.0 has a possibility to define explicit "filters" (see chapter 3.5.8 of http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-complete-v1.0-os.pdf). That is great (at least theoretically). For some reason, perhaps because the AMQP 1.0 filters are a more complex feature with no direct equivalent in the other popular MQPs, its support in applications is limited, diplomatically speaking. 
Thus, for the purpose of this discussion, we can conclude that AMQP 1.0 offers server side filtering that is equally good as in case of 0.9.1. 
From practical point of view, the server side (topic) filtering was tested between IBL and DWD where RabbitMQ with the AMQP 1.0 plugin was used and (possibly more extensively) by myself with Apache Qpid broker.

**Comment by josusky** [comment]
And to answer the main question of this issue "Is Server-Side Filtering a requirement for MQP?", my answers is: "Definitely."

**Comment by antje-s** [comment]
I also think Server-Side Filtering is important especially with the expected increase in data volume in the future.
However, there could be several approaches to this. If we do not want to include possible solutions in the set of allowed/supported ones, there should be good reasons for this. On the other hand, standardisation to a limited quantity is good for the all for cost reasons.

How do we relate the protocol level filtering with the WIS DAR catalogue?
--> The metadata could contain a topic or key value, possibly in the transfer options section.

**Comment by petersilva** [comment]
AMQP provides a lot of flexibility, like keyword routing (which is essentially the same as GTS routing, and we end up with huge routing tables.) A lot of the early work we did with AMQP was deciding features not to use, to pare it down to a subset.

There is a deck prepared about functional motivations for MQP that discusses server side filtering.  The more features we ask for, the more we narrow the scope of protocols that can be considered. The MQTT protocol does topic filtering only.  AMQP v0.9 has topic filtering as an explicit type of exchange.  keyword filtering is not supported natively by MQTT, and likely multiple types of filtering (e.g hierachical topics and keywords used together) is not supported by any protocol.  If we make the server-side filtering requirement too complicated, then we need custom code on the broker.

The brokers are optimized for the types of filtering they support.  When we look through discussions, they specifically avoid regular expressions, for example, for efficiency reasons. Two completely different groups (the AMQP people and the MQTT people) both ended up using wildcarding as their sole pattern matching in hierarchical topics. Probably a good reason for it.

**Comment by petersilva** [comment]
looking at @josusky 's link... I see AMQP 1.0 has "apache.org:legacy-amqp-topic-binding:string"
in https://www.amqp.org/specification/1.0/filters  not sure how to use it yet, but at least it is there.
Did DWD and IBL do some exchanges using such filters?

**Comment by antje-s** [comment]
have looked again in the py-script for the subscription (using proton), as far as I have seen, I have declared a routing key, but it is not used for the queue/create_receiver.

**Comment by antje-s** [comment]
but Jan tested filtering with AMQP1.0 (Qpid) broker: "...and (possibly more extensively) by myself with Apache Qpid broker"

**Comment by josusky** [comment]
Sorry, for confusing you.
1. The AMPQ 1.0 was tested, as far as I know, with server side filtering based on topic (e.g. "some.*.cool.topic.#"), which I tend to call "binding key" filtering (perhaps there is a better term for it) and which is the same old thing as in AMQP 0.9.1 and MQTT.
2. I did not test the other filtering, that is only in AMQP 1.0 and that seems more complex/powerful, because I have not found a way how to make it work with the tools that I have - that is what I referred to as "support in applications is limited". It could be just my lameness. Anyway, as this other filtering is not available (has no paralel) in MQTT, I would not recommend to use it (relay on it) either way.

**Comment by petersilva** [comment]
You can use the same bind verb with all the different types of exchanges, hence the word "binding key", they will be interpreted differently.  "binding key" does not specify how the key is processed.  It just tells the broker to "use this key" ... if a binding key is provided to a topic exchange, it will be interpreted as a topic (with wildcards), if the same key is supplied to a "direct" exchange, the key is a keyword that is interpreted literally (no wildcards).  There is a rabitmq specific extension for "header" exchanges, where the binding key allows one to specify values of multiple headers ( tag-value fields in AMQP messages) to be used for routing (no idea how that is encoded, haven't cared enough.)

I think topic filtering is the generic way to talk about what we are trying to do.

**Comment by petersilva** [comment]
As an example of the effect of this position, which I agree with: Apache Kafka, is based on the concept of logs, that is every entry sent, must be consumed with no server side filtering. Just to confuse things, Kafka has something that they call "topics" which map more or less directly to AMQP "Exchanges"... they are not hierarchical, or nearly as flexible as the MQTT/AMQP usage.  So my expectation is that Kafka would be sort of disqualified from consideration as an official protocol by this.

So Kafka could not be considered an official protocol WIS2 data exchanges.  Of course, unofficially, people could easily feed the messages into a Kafka network and do whatever they wish, that would just be a non-standard usage.

**Comment by josusky** [comment]
I am fine with that.

**Comment by petersilva** [comment]
There seems to be no disagreement.  Will give people more chance to comment, but will close the issue around the next meeting if no dissent arises.

**Comment by petersilva** [comment]
all agreed (committee meeting.)
