### ISSUE TITLE
additional headers in message structure to support mirroring use case.

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#16]
Optional headers... for the file mirroring use case, additional headers will be present:

atime,mtime,mode
man 2 stat - the linux/unix standard file metadata: access time, modification time, and permission (mode bits) the times are in the same date format as the pubTime field. the permission string is four characters intended to be interpreted as traditional octal linux/unix permissions.

examples:

  * 'atime' : '20210108T000040.851336523',
  * 'mtime' : '20210108T000040.851336523' ,
  * 'mode' '644' 

Permits use deployments where it should work in the style of *rsync*.

**Comment by petersilva** [comment]
@josusky hi there? What do you think about adding these as optional headers ?  This is used in our mirroring implementation. It is the last major case that I omitted to simplify proposals to the WMO.

**Comment by josusky** [comment]
The term "optional headers" confuses me a bit. If you mean adding three optional properties into "message-schema.json", I am fine with that.

**Comment by petersilva** [comment]
sorry about that... in Canadian stack (v2) the meta data attributes were implemented using "AMQP headers", and documentation was made to abstract away as little as possible from AMQP, so we  used their word... For v3/wmo work, we want to use ... AMQP and at least, MQTT as well.  Both protocols use the word *headers* with a specific meaning, and that is not what we mean anymore. Is properties the preferred term of art?

**Comment by josusky** [comment]
I guess that JSON terminology is simply a "value" or "name–value pair", but according to http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.2 an object is "An unordered set of properties ..." so I prefer to call it a "property" or "optional property" in this case :-)

**Comment by josusky** [comment]
Hi Peter, to avoid code change at your side, do you encode the "mode" into JSON as integer or as string?
(Your example is not a valid JSON, sorry :-))
In other words, is it:
`"mode": 0644`
or
`"mode": "644"`

**Comment by petersilva** [comment]
I did a string, to ensure readability. I didn't trust people to understand integers interpreted in octal.   Also, these days, an integer is eight bytes, the string is six if you include the quotes.

**Comment by petersilva** [comment]
oops... I think the last comment about size is just wrong... never mind.  anyways, I used strings.

**Comment by josusky** [comment]
Pull request created.
@petersilva, I allegedly said "schemas are a bit useless if they do not exclude anything" - could be, in my age I hardly remember half of what I say. But that inspired me to a question:
Currently only 4 properties are obligatory/required ("pubTime", "baseUrl", "relPath" and "integrity"), what about making "size" obligatory too?

**Comment by petersilva** [comment]
I lied... I thought this was all that was needed for rsync style usage, but there are two other cases of general interest.

Yeah... um... size should be obligatory yes... about integrity... there are two *rsyncish* cases where integrity make no sense:

* symbolic link (just include the *value* of the link in the message, integrity redundant) just opened #21 for that.

* unlink/remove (when a file is removed, the post is generated after the fact, so we cannot calculate the checksum.)
