### ISSUE TITLE
Do we permit space character in topic or file names?

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#17]
I noticed that MQTT, spaces are used often in topic hierarchies. In Linux, spaces in file names are often avoided to prevent issues with escaping spaces in shell scripts. It might be practical for the committee could choose to replace all spaces with _ ? This arises particularly in place names, and this practice is already done manually in TableCCCC.json
where the *centre* field has underscores, while the *name* field does not.  The *centre* field is what is used in the library to build a topic.

If spaces are preent in file names, for example, the library will currently pass them through.  We could decide to replace spaces with underscores in filenames as well.

**Comment by josusky** [comment]
Technically, file names with spaces are usable, but you are right that it could cause problems further downstream. There is one more ugly thing related to them. In URL space shall be encoded as "%20" but for historical reasons some systems use "+" to replace space in URL. The "+" should be encoded as "%2B" so if a file name with space goes through several rounds of encoding and decoding it might get scrambled.

**Comment by josusky** [comment]
Perhaps I am just too old and remember to many old issues, feel free to disregard my comment. But you were warned :-)

**Comment by petersilva** [comment]
full disclosure: I opened the ticket, and I am not immune from Bettridge's law "to any headline that ends in a question mark, the answer is always: no."  My own feeling is that spaces complicate things, and in practice no clarity is lost if people replace them with underscores.  I brought the questions up because I think we should not allow them.  To me, someone needs to defend the honour importance of %20 aka +.

**Comment by petersilva** [comment]
I guess we should take care of banning the period character (topic separator in AMQP) and slash character (topic separator in MQTT) at the same time.

**Comment by josusky** [comment]
The title of this issue is "... space ... in topic or file names". So let's not diverge. Topic separators are, er, a separate topic. And file names ("relPath") naturally contain slash and dot with the usual meaning. No spaces, though. 
Let's close this one (@petersilva please add it to the list for the next meeting).

**Comment by petersilva** [comment]
Answer: No, we do not permit spaces in topic or file names.
