### ISSUE TITLE
Do we need the upper in upper-air? 

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#2]
in the initial version, I had air/upper.  feedback resulted in reverting to upper-air.  The thought occurs that since there is no middle-air, or lower-air, and any observations about air immediately above the ground are covered under land or sea... upper seems extraneous.  we could just as easily say air.

**Comment by antje-s** [comment]
upper-air is an established term in meteorology and therefore I would rather leave it that way, but logically, I agree with you that it is unnecessary

**Comment by petersilva** [comment]
I just noticed that the current tables still include air/upper... I  thought that was already replaced... ok putting it back in master.
it is in the feed now (air/upper is gone to upper-air.) so now this issue makes more sense.

**Comment by josusky** [comment]
In fact, what we call "upper-air measurement" is a in fact a vertical profile, typically starting from the ground and ending somewhere in the stratosphere :-)

**Comment by petersilva** [comment]
I guess we are drifting a bit... but is upper-air only vertical profiles
from ground-based sources? I would think some come from radiosondes
from balloons... so it would travel laterally as it goes up (not entirely
"vertical") Others are from aircraft... where the direction could be
horizontalish... Also... Satellites naturally see the top of the
atmosphere, instead of the bottom (or I guess they see all of it on a clear
day.)

AMDAR as upper-air:
https://www.wmo.int/pages/prog/www/IMOP/meetings/MG-3/Doc.2.3(4)_ET-UGRN.doc
Satellite upper-air data:
https://www.wmo.int/pages/prog/www/IMOP/publications/IOM-121_Upper-Air.pdf

But it is not in scope for us to start re-interpreting words for
meteorology.  I guess the only thing I noticed is that there is no "lower"
or "middle" air... which would intuitively make the "upper" redundant...
there is an obvious benefit to making topic hierarchies more compact, but
if that will confuse people, it is not helpful.

fwiw, George Orwell famously referred to himself as growing up as
upper-lower-middle class (resulting in a 27 class hierachy :-)

**Comment by petersilva** [comment]
I think I give up.  We should just keep upper as it is in wide use, and not our place to change meteorological vocabulary.
