### ISSUE TITLE
Unknown Table C3 entries

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#3]
The tableC3 available on the WMO web site does not list a number of codes which are present in an sample UNIDATA derived product feed:
```

"M":"somewhere/tableC3M",
"N":"0-90n",
"O":"somewhere/tableC3O",
"P":"somewhere/tableC3P",
"S":"0-90s",
"T":"north-america",
"V":"somewhere/tableC3V",
"X":"global",
"Y":"somewhere/tableC3Y",
"Z":"somewhere/tableC3Z"

```

Example bulletins (from the test set included in this repo):
```

 21 - IUSV51_KWBC_151150
topic from CCCC KWBC -> washington_national_meteorological_com_centre_dc (country: us )
ahlpib: ['observation/air/upper', '', 'Upper air\n']
topic from TT/B  "IU" -> "observation/air/upper"
AATopic 1 input: TT=IU, AA=SV, ahlHint={'Description': 'Observational data (Binary coded) - BUFR', 'T2': 'B', 'A1': 'C6', 'A2': 'C3', 'ii': '**', 'priority': '2'}
AATopic 2.5 C6:
C6 self.a1topic=temp/ship
AATopic 4 self.a2topic=self.tableC3[V]=somewhere/tableC3V
topic from AA/C: "SV" -> "temp/ship/somewhere/tableC3V"
country to lookup for GISC: us
topic from ii/C is: "51" -> ""
GISC: Washington country: us topic is: washington_national_meteorological_com_centre_dc/observation/air/upper/temp/ship/somewhere/tableC3V
GISC,country,topic=Washington, us, washington_national_meteorological_com_centre_dc/observation/air/upper/temp/ship/somewhere/tableC3V

```
29 - IUSZ52_KWBC_151235

HEPF98_KWBC_151800
HHOG15_EGRR_290000_efeecc850c17e9650b16fe9e8eb5735d.grib
HHMG20_EGRR_290000_b1e617564322a7c7e6cacb2ee579828a.grib
HRYA92_EGRR_290000_393b2b09047f2cddb6b7ce6df6a768d7.grib

These entries have likely been standardized by people working with these data sets, but the information has not made it back to the WMO tables.

**Comment by petersilva** [comment]
If you see *somewhere/TableC3x* it means we encountered a bulletin which uses x and for which the rest of the header indicates we should use Table C3 should be used, yet there is no entry with the letter x in Table C3.

**Comment by antje-s** [comment]
a good idea to find still missing entries in the tables, for the messages found, we could use the metadata to try to find suitable topic suggestions
