### ISSUE TITLE
Necessity of baseUrl, integrity, pubTime

### ISSUE THREAD

**Issue by public-tatsuya-noyori** [wmo-im/GTStoWIS2#33]
An example of MQP message format is as follows:

>    {  "pubTime" : "20190120T045018.314854383",
>       "baseUrl" : "https://localhost/data",
>       "integrity": {"method": "sha512", "value": "A2KNxvks...S8qfSCw=='},
>       "relPath" : "20190120/WIS/CA/CMC/UpperAir/04/UANT01_CWAO_200445___15103.txt",
>       "size": 457,
>       "content": { "encoding": "utf-8", "value": "encoded bytes from the file" },
>       "retPath" : "4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab"
>    }
https://github.com/wmo-im/GTStoWIS2/tree/main/message_format

An example of HTTP response header is as follows:

>    HTTP/1.1 200 OK
>    Content-Length: 4991260
>    Accept-Ranges: bytes
>    Content-Type: binary/octet-stream
>    Date: Mon, 15 Mar 2021 01:29:47 GMT
>    Etag: "e62bdd0e96e4438b1612d6c5a283b142"
>    Last-Modified: Wed, 03 Mar 2021 00:58:06 GMT
>    Server: AmazonS3
>    X-Amz-Id-2: CHN1UTPM5dH+eGOUfQd3BN7ZHXiL7DD/Te7YQA8HLlWAojJXJb+X1e3JUdTYP0Pj8jUqwFAzHKk=
>    X-Amz-Request-Id: EEYNK74HFN49F6NZ
>    X-Amz-Storage-Class: INTELLIGENT_TIERING

Isn't the "pubTime"/"size"/"content" in MQP message unnecessary because it is included as "Last-Modified"/"Content-Length"/"Content-Type" in the HTTP response header?
Also, isn't the "baseUrl" in MQP message unnecessary because it is the same for all messages?
In the case of S3, the checksum value of "integrity" in MQP message unnecessary because it is included as "ETag" in the HTTP response header?
In the end, doesn't it only need "relpath" as follow?

0190120/WIS/CA/CMC/UpperAir/04/UANT01_CWAO_200445___15103.txt

**Comment by petersilva** [comment]
* The scheme is intended to be protocol independent, working un changed with FTP, SFTP, bittorrent, ipfs, S3, some other unknown protocols, so it just treats transport as something that moves bits. What is provided by underlying protocols varies.

* The protocol must work with multiple hops ( NodeA->NodeB->NodeC) If a file is forwarded across two or three nodes, the pubTime will be the "Last-modified" from the first node onto which the file was placed.  If you just copy the file from nodeA to nodeB, on nodeB the "last-modification time" will be the time it is written on nodeB.  So the times on all the nodes will differ and not be comparable.  

* The baseUrl is used for 3rd party transfer. This is used for a number of use cases:
  * sharded: a main broker in a cluster with n transfer nodes, the baseURL will point to the transfer node with the file on it.
  * forwarding: a broker may elect to forward data from a different source without downloading.
  * it can also vary in time (baseURL can include date)

* etag.  
  * "ETag is an opaque identifier assigned by a web server" ( https://en.wikipedia.org/wiki/HTTP_ETag ) so it is not necessarily calculable by downstream consumers, it is just a tag that must remembered by the downloader.  if the protocol is multi-hop, there is no guarantee that two nodes will use the same tag.  A different implementation may assign a different tag, and thus advertisements from different upstream sources may not be comparable.  Ideally, the method used to derive the identifier is reproducible by the downstream client, hence the use of published checksum algorithms, which provide an additional surety to downloads, in addition to the cache verification function of etags.
   * etag is protocol specific, and not available in ftp, or sftp, or potentially other transfer protocols.  one goal of this mechanism is to allow for easy substitution of transfer protocols.
