### ISSUE TITLE
different topic subtrees for SYNOPs due BUFR vs. TAC

### ISSUE THREAD

**Issue by antje-s** [wmo-im/GTStoWIS2#39]
Currently SYNOPs are contained under different topic trees because they have different values in the underlying WMO tables on the top level (TableA). Should or can this remain, since all TAC messages are replaced by the BUFR and then only one topic tree remains?
The same question applies to IWXXM

**Comment by petersilva** [comment]
Can you provide an example or two? easier to understand concretely.

**Comment by antje-s** [comment]
BUFR - TAC example:
ISMD01EDZW
Observational data (Binary coded) - BUFR Surface/sea level : Main synoptic observations from fixed land stations : 90°E - 0° northern hemisphere (ISMD)
--> topic: v03/WIS/de/offenbach_met_com_centre/observation/surface/land/fixed/synop/main/0-90n/90e-0

SMDL02KWBC
Observational data (FM13) - Surface/sea level : Main synoptic observations
--> v03/WIS/us/washington_national_meteorological_com_centre_dc/surface/land/synop/main/de

**Comment by petersilva** [comment]
moot. topic hierarchy discussion is now for: https://github.com/wmo-im/wis2-topic-hierarchy
