### ISSUE TITLE
Formalizing Recommendations/Standards

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#40]
As a Deliverable, we need to produce more formal documents.  Chatted a bit with @kurt-hectic and @efucile and we think:

* an restructured text (.rst) in the the repository is a good starting point.  
* add a folder to repository  to contain them.  doc/ ?  Recommendations/, Specification? 
* Next consideration is the structure of the document?  What are the required headings?  Do we base on IETF RFCS? Python PEPS? 
* Produce a draft.

**Comment by petersilva** [comment]
format inspiration:
* https://www.rfc-editor.org/rfc/pdfrfc/rfc7322.txt.pdf
*

**Comment by josusky** [comment]
Hi @petersilva we have missed you today at the teleconference.
The action, that resulted from the discussion is, as far as I understand it, to create a human readable document that would help people to put their products into the topic hierarchy, i.e. to list possible values at each level in the hierarchy (starting from the root) and/or recommendation for reasonable names at levels where the values are not fixed.

**Comment by petersilva** [comment]
ET-AT has taken over responsibility for the deliverables, so no longer needed.
further discussion here: https://github.com/wmo-im/wis2-notification-message
