### ISSUE TITLE
country code for international organisations in TableCCCC.json

### ISSUE THREAD

**Issue by antje-s** [wmo-im/GTStoWIS2#42]
Which country code should international organizations be registered with?
There are currently different variants in the TableCCCC.json
e.g.
"IAEA":{"centre":"international_atomic_energy_agency", "name":"International Atomic Energy Agency", "country_short":"de",  "comment":""},
"EUMG":{"centre":"eumetsat_darmstadt", "name":"EUMETSAT (Darmstadt)", "country_short":"eu", "gisc":"Offenbach",  "comment":""},

Should we use:
- "zz" as "unknown or unspecified country"
- country code of primary GISC of DCPC
- "eu" for Europe for European Organizations
- ??

**Comment by petersilva** [comment]
see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2  which is the underlying standard we are supposed to be leveraging.
it has provision for "eu", and for this case "un."

**Comment by antje-s** [comment]
Shall we update "UNO" in TableCCCC for IAEA?

**Comment by petersilva** [comment]
yes. as per: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Exceptional_reservations

**Comment by antje-s** [comment]
updated TableCCCC.json
