### ISSUE TITLE
Add missing CCCC in TableCCCC.json if only country is known?

### ISSUE THREAD

**Issue by antje-s** [wmo-im/GTStoWIS2#43]
Should we also add CCCC to TableCCCC.json for which we only know the country e.g. in the form
"LOXB":{"centre":"", "name":"", "country_short":"at",  "comment":""},

Attached is a list with probably missing CCCCs
Austria:  LOXB,  
Czechia:  LKBC,  LKPJ,  OKLA,  OKLI,  OKPD,  
Norway:  ENVN, ENXX
Sweden:   EQMB, ESCK, ESCR, ESIA, ESXA, ESXB, ESXC, ESXD, ESXE, ESXG, ESXH,  ESXI, ESXX, ESXY, SMHI, 
Jordan:   OJSM,
Montenegro:  LYBG,  
Turkey:  LTFM,  
Eumetsat:  EUMC,  
Greece:  LGWL,  
Estonia:  EEEI,  
Cyprus:  LCRO,  
Israel:  LLER,  
Poland:  SOPR,  
Kenya:  HKCM,  HKMV,  
Belarus:  URMS, 
Uruguay:  SURU,  SUSU,  
Peru:  SPMF,  
Paraguay:  SGFA,  
Mali: EQGA,  
Eritrea: HHAA,  
Sudan: HSSK,  
Cambodia: VDSV,  
Mauritania: KCHO,  
Angola: KNAS,  
Oman: OODQ,
United_Arab_Emirates: OMAM,  OETN,
Syrian Arab Republic: OSDO,  OSFI,  
Afghanistan: OABK,  OAHE,OAMR, OARH,
Spain: GECE,  LEAG, LEAO, LEBT, LEEC, LEMI,  LERL, LESB, LETL, 
France: IBLZ,  LFXV,  
Iceland: BIGJ,  BITN, 
Iraq: OEBI, ORBA,  ORBU,  ORKM,
Belgium: EBOC,  
Brazil: SBAO,  SBCW,  SBEZ, SBJE,  
Burkina Faso: DHHH,   DHHV,
Guyana: SYEC,  
Madagascar: FMMM,  FMMN, 
Pakistan: OPDT,  OPIS, OPLC, OPLR,  
Swaziland: FDSK,  
Zambia: FLML,  FLMS,  
China:  BCGZ,  GDZJ, ZPLJ, ZSJO,  ZSNO,  ZSQZ, ZSXS,  
India: AFHQ,  VADU, VAJL,  VANB, VANO,  VANR, VAOZ, VASU, VEBI, VEDG, VEKO, VEJT,  VELP, VEMR,  VEPG, VEPY, VERB,  VERP, VETZ, VEVI,  VEVS,  VIBR, VICG, VICH, VIDN, VIGG,  VIHS,  VIJU, VIKG, VILD, VILH, VIPT,  VISM, VOAM, VOAN, VOAR, VOAT,  VOBB, VOGB, VOHB,  VOHZ, VOIN,  VOJV, VOKL, VOKN, VOLT, VOMN, VOMP,  VOND,  VOOG,  VOPC, VORD,  VORY, VOSM,  VOTK,  VOTA,  
Morocco:  GMCH,  GMFA,  GMFB,  GMFC,  GMMB,  GMMD,  GMMJ,  GMTL,    
Russian Federation: RUKG,  UUAG,   
South Africa: FABT,  FATV,  FATH,
Saudi Arabia:  OEAR,  OEMN,  OWDR,   
Qatar:  OTBI,  
United Kingdom:  EGRX,  
ECMWF: ECMX,  
Indonesia: WAHH,  WICC,  
New Zealand : NZGP,  PLCH, 
Australia : YBBB,  YBRF,  YMMC,  YMRF, YPRF,  YRMF,    
Fiji: NADI,  
Canada: CAWE,  CAYT,  CEWA,  CBBC,  CEWM,  CEWO,  CWAE,  CWGZ,  CWMW,  CWQB,  CWQI,  CWSE,  CWSW,  CWVK,  CWWG,  CXWI,  CYAB,  CYAM,  CYAS,  CYAT,  CYAY,  CYAZ,  CYBB,  CYBD, CYBK,  CYBL,  CYBQ,  CYBU,  CYBV,  CYBW,  CYBX,  
CYCA,  CYCB,  CYCD,  CYCG,  CYCK,  CYCO,  CYCP,  CYCQ,  CYCS,  CYCX,  CYCY,  CYDC,  CYDF,  CYDL,  CYDP,  CYDQ,  CYEK,  CYER,  CYFO,  CYFR,  CYFT,  CYGE,  CYGH,  CYGK,  CYGQ,  CYGR, CYGT,  CYGV,  CYGW,  CYGX,  CYHA,  CYHD,  CYHI,  CYHK,  
CYHM,  CYHU,  CYHY, CYIK,  CYIN,  CYIO,  CYIV,  CYJF,  CYKD,  CYKF,  CYKG,  CYKJ,  CYKO,  CYKP,  CYKQ,  CYKY,  CYKZ,  
CYLA,  CYLC,  CYLD,  CYLH,  CYLJ,  CYLK,  CYLL,  CYLU,  CYLW,  CYMA,  CYMH,  CYMO,  CYMU,  CYNA,  CYMD,  CYNC,  CYND,  CYNE,  CYOC,  CYOO,  CYPC,  CYPD,  CYPE,  CYPO,  CYPQ,  CYPW,  CYPX,  CYPY,  CYQF,  CYQK,  CYQV,  CYQZ,  CYRA,  CYRQ,  
CYRT,  CYSF,  CYSK,  CYSN, CYSP,  CYSY,  CYTE,  CYTH,  CYTL,  CYTQ,  CYTZ,  CYUB,  CYUT,  CYUX,  CYVL,  CYVM,  CYVT,  CYWE,  CYWH,  CYWJ,  CYWK,  CYWY,  CYXH,  CYXN,  CYXP,  CYXQ, CYXT,  CYYG,  CYYH, CYYL, CYZG,  CYZH,  CYZR,  CYZS,  CYZU,  CZBF,  CZEM,  CZFA,  CZFN,  CZFM,  CZMD,  CZMT,  CZPC,  CZSJ,  CZST,  CZUM, CZVL,  
Cayman Islands: MWRC,  
El Salvador: MSDS,  
PUERTO RICO: SANJ,  
SAINT KITTS AND NEVIS: TKUR,  
United States of America: KWYZ, KDHL,  KWMX,  KCRW,  KCYA,  KNTA,  KNTC,  KNYC,  KOKC,  KOLM,  KOMA,  KOTH, KROW,  KRST,  
KSAC,  KSAN,  KSAT,  KSAV,  KSCK,  KSDF,  KSEA,  PHLI,  PPRH,  KAXN,  KAYS,  KBAB,  KBAF,  KBCE,  KBCQ,  KBDL,  KBDR,  KBFD,  
KBFF,  KCID,  KCIR,  KCKB,  KCKL,  KCLL,  KCLT,  KCMF,  KCMH,  KCMI,  KCNK,  KCNM,  KCNU,  KCOA,  KCOD,  KCOM,  KCON,  
KCOS,  KCOT,  KCOU,  KCPR,  KCQT,  KCRH,  KCRT,  KCSG,  KCSH,  KCSM,  KCSV,  KCTB,  KCTY,  KCVG,  KCVS,  KCXY,  KCYP,  KJLN,  
KJOS,  KNTD,  KNTU,  KNUW,  KNWC,  KNXX,  KNYG,  KNZC,  KNZW,  KNZY,  KOAK,  KODX,  KOFK,  KONT, KORD,  KORF,  KORH,  
KOTM,  KOZR,  KRME,  KRMG,  KRNO,  KROA,  KROC,  KRSL,  KRWA,  KRWF,  KRWL,  KRYY,  KSAF,  KSAW,  KSBA,  KSBD,  KSBN,  KSBP,  KSBT,  KSBY,  KSCR,  KSCS,  PHNC,  PHNL,  PHNY,  PWAK,

**Comment by petersilva** [comment]
Feel free to add entries if you wish. To me, this is a subset of #4. There are about 15,000 airports in the world, and our CCCC code is 6000 and a lot of the entries are not airports, so we are clearly missing the majority of such codes in this table.  Perhaps a more systematic approache is adviseable, some kind of DB import from IATA/ICAO?

**Comment by petersilva** [comment]
@chenxiaoxia2019 info about added some CCCC's...  already in our .json version.
