### ISSUE TITLE
Are "intermediate", "non-standard", "under12hours" useful?

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#45]
Got some feedback that the "intermediate" qualification of observations is perhaps an obsolete temporal attribute that is of little use in practice.  If people want an ob, they want all the obs for that place, and don't care if it is on a synoptic hour, or an intermediate one.  suggestion is to drop intermediate from the tables.

```
TableB.json:		"I": "land/synop/intermediate",
TableC6.json:      "I":{ "ii" : { "45": "land/fixed/synop/intermediate",
TableC6.json:                     "59": "land/mobile/synop/intermediate" }},
TableC7.json:"KSI": { "ii": { "45" : "obsevation/land/intermediate",
TableC7.json:                 "59" : "observation/land/mobile/intermediate" }},

```

**Comment by petersilva** [comment]
20210831T21/WIS/de/offenbach_met_com_centre/observation/surface/land/fixed/synop

there are two sub-directories:   *intermediate* (ISID0x EDZW ... ) , and *non-standard* (has a single ISND02_EDZW in it)

Is putting those two groups in separate directories useful?

Similarly.  If I look at:

/~pas037/WMO_Sketch/20210831T21/WIS/de/offenbach/forecast/aviation/taf/under12hours/de

Is the *under12hours* ... the valid time of the forecast, helpful?  I think anyone wants taf's they want all tafs for a given area, and the time constraint is not helpful in selection.

**Comment by petersilva** [comment]
On the other hand, I think all of those would be good to have in the file name #41 ... and not the topic.

**Comment by petersilva** [comment]
```

fractal% grep non-standard *
grep: __pycache__: Is a directory
TableB.json:		"N": "land/synop/non-standard",
TableC6.json:      "N":{ "ii":  { "45": "land/fixed/synop/non-standard",
TableC6.json:                     "59": "land/mobile/synop/non-standard" }},
TableC7.json:"KSN": { "ii": { "45" : "observation/land/non-standard",
TableC7.json:                 "59" : "observation/land/mobile/non-standard" }},
fractal% 
fractal% grep under12 *.json
TableB.json:		"C": "aviation/taf/under12hours",
TableB.json:		"C": "taf/under12hours",
fractal% 
fractal% grep over12 *.json
TableB.json:		"T": "aviation/taf/over12hours",
TableB.json:		"T": "taf/over12hours",
fractal% 


```

**Comment by antje-s** [comment]
Do the numerical predictions distinguish between main, intermediate and non-standard? The information should probably be included, but whether in the filename or in the topic, that is the question...
From my point of view, in terms of increasing automation and shorter intervals between observation times, it might be better to include it in the filename. 
But we should check with the forecasting experts...

**Comment by petersilva** [comment]
I don't think NWP has the concept of main vs. intermediate vs. non-standard (not to mention SPECI.) They have different things, like nowcasting, deterministic vs. ensemble, resolution (4km?), grid (topology and coverage) global, LAM, etc...

**Comment by petersilva** [comment]
current practice example...

Our data mart is here: http://hpfx.collab.science.gc.ca/20210902/WXO-DD/
there are model_XXXX where XXXX is the name of the model, then next folder level down, varies by run.. for example model_hrdps (high resolution deterministic prediction system) and is the same model run over a bunch of different domains: east (central Canada and the maritimes), west (BC, Alberta, Yukon, NWT), North (arctic), prairies (everything else.)

model_gem_global, the sub-directories have different resolutions of data available.

http://hpfx.collab.science.gc.ca/20210902/WXO-DD/model_gem_global/25km/grib2/lat_lon/12/006/

 CMC_glb_ABSV_ISBL_200_latlon.24x.24_2021090212_P006.grib2

**Comment by antje-s** [comment]
Sorry for the misunderstanding, it was not about the different numerical weather forecast products, but about the data assimilation. But probably it is not distinguished, only the timely receipt is relevant...

**Comment by petersilva** [comment]
I chatted up one of our NWP assimilation people.  He confirmed that they ingest the data without using those distinctions.

**Comment by petersilva** [comment]
replaced by: https://github.com/wmo-im/wis2-topic-hierarchy
