### ISSUE TITLE
optimize topic tree no1: delete addressedMessage.

### ISSUE THREAD

**Issue by antje-s** [wmo-im/GTStoWIS2#48]
For the data currently sent via GTS, an automatic assignment to suitable topics is found with current GTStoWIS2 topic mapper, but it could be optimized for AHL and GTS independent data. A simple topic-tree should be available to allow an easy and quick search for a suitable topic for both publishing and subscribing.

To simplify, there are several suggestions, each of which I would put in a separate issue so that we can discuss them one by one.

1) addressedMessage
current topic subtree (T1="B"):  
- addressedMessage

proposal: 
- DELETE subtree, not needed for general MQT exchange. 
(Messages for specific groups could be done in the future e.g. via separate topic tree, e.g. for own AoR)

**Comment by petersilva** [comment]
I agree. I don't see the point of addressedMessages in pub-sub.  If we ever need it, we can always add it back in a later revision.

We can put this in the agenda for next meeting, to get others to examine.  I am aware of no issues with this.

**Comment by antje-s** [comment]
...should not occur but left in for now
"B" --> "topic": "notes/addressed/" (Could be deleted in TableA.json)
