### ISSUE TITLE
eventually will rename master branch to main.

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#6]
Some are concerned about connotations of "master" as the default branch in git.  ( https://www.bbc.com/news/technology-53050955#:~:text=The%20world's%20biggest%20site%20for,code%20%2D%20to%20a%20neutral%20term. )

The consensus seems to be to use "main" instead.  tools are evolving to automate such changes, ( https://github.com/github/renaming ) but if repositories are not particularly active, the change can be done 
without tooling support.

Will probably just proceed to do that in the next week or two, unless there are objections.

**Comment by josusky** [comment]
Go for it.

**Comment by petersilva** [comment]
@efucile  I do not seem to have admin rights to change the default branch on this repository.
I have created a  branch called "main" you would need to use repository settings to designate it as the default branch.
Thanks.

**Comment by petersilva** [comment]
@efucile can you change the "default" branch for this repository to be "main" instead of "master" ?
I have started committing to main, and it is starting to be confusing for the default to still be "master"
for exampe, I have committed the message_format to main.
