### ISSUE TITLE
optimize topic tree no17: observation/pictoral/radar --> radar/pictoral

### ISSUE THREAD

**Issue by antje-s** [wmo-im/GTStoWIS2#65]
current topic subtree (T1="I", T2="P", A1="C | R"):
observation/pictoral/radar/composite
observation/pictoral/radar/

proposal:
MOVE TO:
radar/pictoral

**Comment by antje-s** [comment]
#51

**Comment by petersilva** [comment]
Question: should all monitoring data of any kind be under observation?

observation/radar
observation/satellite
observation/surface
observation/vertical_profile
observation/aerosonde
observation/marine

synthetic imagery (prediction of future GOES images, for example) would be under...

forecast/satellite ?



?

**Comment by antje-s** [comment]
Sounds good from my point of view. It's just important to make it consistent.
If we have e.g. satellite separately, we should also separate radar. 
But to have all obs messages under "observation" would be better
