### ISSUE TITLE
Is queue sharing a requirement for MQP?

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#70]
Similar to the discussion about Server-side filtering. The original AMQP (v<=0.9) has a concept of queues, and one can have multiple connections to the same queue from different processes, even on different machines, and they can consume messages from the same, shared, queue.   This feature also available in MQTTv5 where it is known as "shared subscriptions"

With this feature, when a particular subscription is running too slowly, we just add processes to the subscription, the additional processes can download the messages in parallel to get important performance improvements.

This is a key element in deployment of AMQP so far, and it is very helpful in practice.  Should this be another aspect of protocols used to define which protocols are acceptable?

e.g. MQTT v3 does not have shared subscriptions and so would be excluded by this requirement.

**Comment by davidpodeur** [comment]
I think that yes, queue sharing is a requirement as It is crucial:
- to avoid "slow consumers"
- to speed up messages retrieval when network  latency is high

MQTT v5 supports shared queues and would hence be the only MQTT version supported (no MQTT v3).

**Comment by antje-s** [comment]
From my point of view "shared subscription" is a good reason to decide for MQTT version5

**Comment by petersilva** [comment]
Agree that queue sharing is a mandatory requirement for MQP's adopted.
