### ISSUE TITLE
use 3-letter country codes, instead of two letter. (ET-W2AT feedback)

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#74]
believe the WIGOS station ID uses the 3 digit ISO country codes as the issuer of identifier. Would it make sense to use the same for both? (Dave Berry.)

**Comment by antje-s** [comment]
a harmonization would certainly be a good idea

**Comment by josusky** [comment]
@petersilva the WIGOS ID contains 3-digits, not 3-letters. That is Canada would be "124" instead of "CA" or "CAN". I agree with some harmonisation, I am just a bit sad that it becomes less human readable.
Here is an example: https://oscar.wmo.int/surface/#/search/station/stationReportDetails/0-124-0-71134

**Comment by petersilva** [comment]
oh... that's not good... does the 124 refer to the issuing organization or the geographic extent of the product?

**Comment by josusky** [comment]
Well, it is a station identifier. The code refers to the "Issuer of Identifier" - that is either country or WMO program (for legacy identifiers). More can be found at https://community.wmo.int/wigos-station-identifier .
Now, we (can) use it for slightly different purpose, I was just trying to point out that WIGOS uses the numeric code.

**Comment by petersilva** [comment]
reading through your link, they give the example of Brazil, and there is a discussion of INMET's approach.

In there, it describes the number as "Issuer of Identifier" ... so it is a number for the WMO member state that issues the identifier, which exactly matches what we are trying to do. but yeah... 3 digits is a step backwared in readability.

um... it's a sharepoint link... brace yourself:
https://wmoomm.sharepoint.com/sites/wmocpdb/eve_activityarea/Forms/AllItems.aspx?id=%2Fsites%2Fwmocpdb%2Feve%5Factivityarea%2FWMO%20Integrated%20Global%20Observing%20System%20%28WIGOS%29%5F99452102%2D7575%2De911%2Da98e%2D000d3a44bd9c%2FWSI%2FWIGOS%5FStation%5FIdentifiers%5FBrazil%5Fv2%2Epdf&parent=%2Fsites%2Fwmocpdb%2Feve%5Factivityarea%2FWMO%20Integrated%20Global%20Observing%20System%20%28WIGOS%29%5F99452102%2D7575%2De911%2Da98e%2D000d3a44bd9c%2FWSI&p=true

**Comment by petersilva** [comment]
ET-AT has clarified at 2022/05/09 meeting that they don't want three digits, they just really prefer three characters, and three characters makes sense in a string context like a topic hierarchy.  I see no problems with this change.

**Comment by josusky** [comment]
OK, the three-letter ID is not controversial at all, let's close this (officially during the next meeting?).

**Comment by petersilva** [comment]
Agree on closing, but it should be done with a branch that updates the module so that it works as agreed (as in @antje-s 's branch.) otherwise, after we agree, we need to open a new issue to adjust the library to match the expectation, which seem a bit redundant. Also, actually impliementing the change in the library is good discipline for us... to make sure that whatever we decide actually works (hsd s reference implementation.)

**Comment by petersilva** [comment]
With the general agreement at committee and the appropriate branch merged, we have successfully accepted this change.
