### ISSUE TITLE
Use STAC for payload: no

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#75]
In relation, particularly with @petersilva contention that we should add geo and time extent specificiations to MQP publication,
@tomkralidis mentioned STAC item as perhaps an appropriate standard to adopt for the payload message for MQP, as it has fields that would encompass those.  Two birds with one stone, and the "standard" records should be attractive to a larger community. Tom also mentioned the availability of extensions (plugins?) not sure of the terminology and that MQP could become a sort of dialect of STAC.

https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md

(insert Tom's example here...)

feed back from @petersilva  so far:

* Tom's example included all the fields from the MQP payload as additional fields in various parts of the STAC payload. There were no shared fields that could be re-used. In fact it generated redundancy, where the same information must be specified redundantly both in split URL's and combined ones to satisfy MQP and STAC communities.  Since the fields are different and added, existing STAC users will just see additional fields, with no particular meaning attached.
* I looked at some sample STAC item records, and they were about 1K, I looked at some of current mqp payloads, which include some extenions, and they were about 430 bytes.  so today, the size penalty is currently at least > 2:1  (caveat: tiny sample size)
* There is a lot to digest and understand in stac, and it isn't clear there is any value (for data distribution) in doing so. Tags to grok: relation, self, root, parent, collection, derived_from, overview, data, metadata, type (at least three different type fields in the stac item record.)  Taking one field as an example "roles" are one of: "thumbnail", "overview", "data", and "metadata".  
* in the spec, it says "_Data providers are advised to be liberal with the links section, to describe things like the Catalog an Item is in, related Items, parent or child Items (modeled in different ways, like an 'acquisition' or derived data). It is allowed to add additional fields such as a title and type_." I looked at some sample STAC records that were 1000 bytes, and they were very sparse. I expect STAC records to grow larger over time.
* while it is possible to compose two different jsons into one combine one, it is unclear that either will know what to do with the fields from the other domain, or derive any benefit.
* keep in mind that most MQP payloads will be discarded, that they are not for discovery, but only for timely retrieval of datasets that have been discovered using an md catalog, and then programmed for download.  Expect most recipients to receive multiple messages for the same data item multiple times.
* according to the spec: _It is "STRONGLY RECOMMENDED" to include links to thumbnails._.. more payload bloat.

I think that STAC records created for MQP will look barren and "wrong" to MD aficionados and catalog maintainers, and there will be a terrible tension.  Ideally... multiple stac records for the same products will exist, one for MQP and another for real cataloguing, which kind of argues against the proposal.

The MQP payload is supposed to be the minimum metadata to decide whether the corresponding data should be downloaded.
the STAC record is full-blown metadata, which has no upper-bound in size.  MQP should have some sort of pointer to metadata, and not include metadata that isn't strictly relevant to data transfer.

**Comment by petersilva** [comment]
This was discussed at W2AT, and the consensus I heard agreed that it was a considerably expansion in payload size and we should think carefully before taking that on.  The examination of the existing payload protocol from TT-protocols was reviewed and found to be sufficient for what we want from MQP for the time being.  It is understood that JSONS can be easily embedded in one another, and there are many possibilities once that can of worms is opened.  One example is cloud events ( see #73 )

**Comment by josusky** [comment]
I agree with @petersilva that using STAC as a data notification format would be in fact "abusing". It is designed for the description of metadata catalogue items. If we stripped it to the minimum that we need, the result would be confusing for metadata experts (and their software) while turning our notifications into real metadata items would be a significant effort for us with a possible negative impact on performance.

**Comment by petersilva** [comment]
Adjusted title to reflect what I gather is the consensus... will formally close at next meeting it stays clear.

**Comment by petersilva** [comment]
no longer tt-protocols concern: https://github.com/wmo-im/wis2-notification-message
