### ISSUE TITLE
Add version tag to payload

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#79]
At ET-AT on 2022/04/05, a suggestion to replace the version in the topic hierarchy with one in the payload.
The observations was that once the message is downloaded, it is unavailable.  so having the version in the message is good, for programs processing the messages.

Observations
-----------------

* people are assuming up on host/in memory representation is the same as on the wire, which is simpler for sure, but not necessary.  What we send on the wire could have the v03 in the topic tree, and we could declare a convention to, when we read it in, turn that into a version tag. and convert back on transmission.  I guess that is some complexity, but it would save a few characters.  ( about 10. )
* the version cannot be selected for by server-side processing when it is only in the message payload, and not the topic hierarchy.  So for situations where one is migrating from v03 to v04, the client must receive double the messages, and reject the ones from the improper version.  
* having the client have to reject the improper version makes seamless rejection of new data by old configs not work... all the old clients have to have rejection of the new format added before you can start posting new format ones.  This is a barrier significant enough that using the same channel for version transitions is no longer possible.  one would, in practice, establish another channel for the new version. Making a change of channel part of every such upgrade. ( e.g. xpublic for current active users, xpublic4 for users of the new format... whereas formerly they could be mixed on the same channel transparently.)

**Comment by antje-s** [comment]
Would it not also be possible to simply accept certain versions on the client side? Then upgrades could take place at any time without problems...
However remains also from my view that we have unused traffic, since the client would like actually only a certain version of the message format and not all, so that in practice probably again a separation would develop over time --> thus from my view the version should remain in the topic, if necessary it could be taken up additionally also in the message, which should not be actually necessary however. On the client side, the message is evaluated directly or discarded and the topic value is still known when it is received.

**Comment by petersilva** [comment]
* yes, every client can, ahead of time, determine which version to accept.  Everyone will put initially "I only accept v03" in their code, which will serve no purpose until v04 comes out.   And one will have to build test cases to make sure that selection criteria works. It is asking for considerable foresight.
* during migrations all clients will get double the message traffic, since server-side filtering is not possible (on a single channel) so the messages routed from the broker will have old and new messages, and the client will reject the old ones at first and the new ones later, but always have to deal with double the flow until the migration is done.

It's just more cumbersome, and uses more bandwidth... probably the approach would change people would use a different channel rather than mixing message versions on the same channel, in order to avoid the double message problem.
so then each message format upgrade involves creating channels instead of just having a new topic hierarchy on a single channel.

**Comment by petersilva** [comment]
Can we make everyone happy if we just have a convention where, we take the version from the topic tree, and create a field in the in-memory version of the message, as requested? It answers the request use case.   that way the tail end of the topic for the message will come from   "version" / os.path.basename(relPath)   (or whatever relPath gets renamed to.)

**Comment by petersilva** [comment]
Please note that the elegance of having the version tag is in the topic hierarchy is visible for inspection in the Canadian feed for WMO experiments. Currently feeding both v03 format (current tt-protocols recommendation.) and v04 format (idiomatic  geojson implementation.)  one can pick which version to use, and the selection is done server side.

**Comment by petersilva** [comment]
Also note that what version in this discussion is is really and encoding format... so rather than using numericalish formats, we could us identifiers, like "geojson", for the format, and what we have been calling "version" is more generally termed encoding format.

**Comment by josusky** [comment]
Having version as part of the topic is very useful and there is no reason to drop it. But we can add it to the message itself too as some sort of redundancy. It is by far not as controversial as other changes proposed by ET-W2AT.

**Comment by petersilva** [comment]
further discussion here: https://github.com/wmo-im/wis2-notification-message
