### ISSUE TITLE
MQP message structure

### ISSUE THREAD

**Issue by kurt-hectic** [wmo-im/GTStoWIS2#8]
How should the message structure for the exchange of WIS data through MQP look like?
What is the maximum message size? 

Some relevant requirements:
- include a link to the actual data, in case the data is big
- carry the actual data as payload if it does not exceed the maximum message size
..

Is there a formal way to specify a message structure, e.g JSON schema or similar?

**Comment by josusky** [comment]
The message/notification structure has been defined in the scope of "wmo_mesh" project, see https://github.com/MetPX/wmo_mesh/blob/master/message-schema.json

**Comment by petersilva** [comment]
copied into this repository now: https://github.com/wmo-im/GTStoWIS2/tree/main/message_format
I think this topic can be closed (changes to the message structure will be dealt with individual issues.)
