### ISSUE TITLE
Add "topic" to the payload (which is actually just what relPath already is)

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#80]
ET-AT asked for the "topic" to be included in the payload.  ET-AT's definition of "topic" excludes the version information (v03), and the channel information (e.g. xpublic), and any of the details for a shared subscription ( e.g. $shared/client-id ) on MQTT,  the real topic for a consumer would issue to "subscribe" verbs in the API with relative topic: ca/canadianmet/observations/surface/... would be:
```

    $shared/client-id-for-shared-subscriber/xpublic/v03/ca/canadianmet/observations/surface

```
so what is being called "topic" isn't the actual topic at all. it's actually identical to the relPath (without the file name)

* To me, it is confusing to refer to this as "topic" because it is actually a relative topic, an invariant identical in purpose and form to relPath, and not the full topic actually used for message publication, 
* ET-AT added a new field that would seem to be identical to the filename, "id:" or not... unclear.

I don't see any value in changing the names, there isn't any semantic benefit, and it obfuscates the obviously simplest representation of the meaning "relative path"

**Comment by petersilva** [comment]
It is pretty much assumed that implementations would be free to add the real "topic" of a message to their dictionaries when they read the message in for processing.  The Canadian stack has never found a need to do this though, building the topic tree from the relative path.  to extract what ET-AT is referring to as "topic" from relpath, use os.path.dirname()

**Comment by kaiwirt** [comment]
In most of the cases, centers already have ways to provide data. That is they already implemented directory structures, filenames etc. What they need is a mapping on where to put that data into the topic hierarchy. Clearly os.path.dirname() will not work for most of them unless they are restructuring their data (which means inform customers, users, etc... and which is likely not to happen).

So, if the outcome is "topic", then i think that naming the corresponding property topic is more speaking than relPath. But then again to me names are just names. The issue is, we need to define _what_ to put into the message at which item of the message.

**Comment by petersilva** [comment]
I don't have any objection to changing names... but "topic" is confusing, because the messages do have a topic, and the actual topic is different from this topic... so every message will have two "topics" and no-one will never know which topic is being referred to.  People want to abuse "id:" if people are happy with having the full topic in there, with a produts specifier at the end, then that's fine... it's identical to relPath.

**Comment by petersilva** [comment]
The purpose of relPath was to be an identifier, it does not imply or require anything about layout of files on disk, although simplest would be to just reflect the topic hiearchy on disk... if you don't do that, then you are required to specify an alternate path... which is exactly what retPath is for.   but since relPath ( or id: or subtopic?) is still needed for the global identifiier for dedup.

**Comment by petersilva** [comment]
from Raoult Baudoin: 

 ```

topic => taxonomy

```
use of that _taxonomy_ will not be confusing.  but it is OK to have the item identifier (aka "id" aka file name ) at the end as part of the taxonomy or will that confuse people who know about taxonomies?

**Comment by petersilva** [comment]
further discussion here: https://github.com/wmo-im/wis2-notification-message
