### ISSUE TITLE
Making integrity optional, reviewing duplicate suppression method.

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#84]
feedback from ET-AT that many API cases, a checksum is not feasible. The approach for such cases upto now, was to request such services to use another integrity method... there is "arbitrary" meaning a method used opaque to the transfer mode.  In many common cases, the id of the product itself, where the id could be either randomish uuid type value, or something more based on the topic hierarchy (like v03-relPath)

**Comment by josusky** [comment]
> The integrity field specifies a checksum to be applied to the data to ensure that the download is accurate. A specific set of methods for calculating the checksum algorithms will be prescribed:
> 
> "sha512" -- the Secure Hash Algorithm 512 bits, value is base64 encoded.
> "arbitrary" -- an arbitrary string is used to identify the value.
> ...
(https://github.com/wmo-im/GTStoWIS2/tree/main/message_format)
We already allow "arbitrary" method for the property "integrity". It can be UUID if it is convenient for some data providers, or something else. I am not sure if making the whole this optional would be of any help.

**Comment by petersilva** [comment]
The idea of optional was floated for the case where the name itself (or data-id) is sufficient.  there will only ever be one item sent out with a single data-id.  In that case, the contention is that we don't need an additional field for dedupe.

**Comment by petersilva** [comment]
* The use case is the "Web services" where producing the message would require reading the entire dataset being announced.  
* some products are "unique" entirely based on their "name"
* We also have "arbitrary" integrity method to deal with the case where content-based.
