### ISSUE TITLE
meaning/specification of id in GEOjson records.

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#85]
from #78, ET-AT is asking for replacement of RelPath by id.  and a topic.

in v03, 
id is chosen because it is almost required in geojson... but all existing examples:
* appear to be a means of naming individual features in featureCollection record.
* ET-AT is proposing it to use for duplicate suppression, in which case it needs to be globally unique.

So the id can be a uuid or some other randomish generated key with a very wide scope.

In the same message payload, we also need/want to have the topic hierarchy. and logically products in a different topic hierarchy are not the same, so including the topic hierarchy in the id makes for a shorter key.

So then the id will need to contain the topic hierarchy, and some sort of record to identify this product or record within the topic.  in my mind this is exactly the function of relPath in v03 format.  so it would amount to renaming v03 'relPath' fo v04 'id'

**Comment by josusky** [comment]
For de-duplication we have the "integrity" field. We could split the "relPath" into the _topic/hierarchy_ part and the _instance name/ID_ part as that is its meaning, as I have mentioned in https://github.com/wmo-im/GTStoWIS2/issues/82#issuecomment-1102405834 but would that really help? On one hand we have been asked not to separate "baseURL" that is difficult to separate (once joined with the "path" element), and on the other hand we would split something that is easy to separate. Confusing.

**Comment by petersilva** [comment]
based on updated 2022/05/09  "id" is again a uuid style thing, but data_id is essentially the same as relPath.

**Comment by josusky** [comment]
As I already stated during our teleconference, I am OK with an "id" field that I do not use, as long as there is a useful one. The "data_id", is a good name for it. I will add it to the new proposal of the schema (issue #90) and we can close this one.
