### ISSUE TITLE
GeoJSON  second proposal (continuing work with ET-AT)

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#90]
@josusky can you produce an updated spec and examples based on latest discussions?

background:
 #78

**Comment by antje-s** [comment]
Currently I wonder if we could put "links" under "properties". Then we are closer to the geoJSON standard (https://geojson.org/) . or are there reasons against it?

**Comment by petersilva** [comment]
@antje-s have a look at #86 :

* syntax of each link is from RFC8288   https://datatracker.ietf.org/doc/html/rfc8288
* use of "links" element is from OGC-API...  ( http://docs.ogc.org/DRAFTS/19-072.html#link-conventions )

interop is the rationale.

**Comment by petersilva** [comment]
closing, as ET-AT now has their own propoal. deferring:

https://github.com/wmo-im/wis2-notification-message
